// Mocks generated by Mockito 5.4.2 from annotations
// in switch_bot_frontend/test/mocks/mock_socket.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:socket_io_client/src/manager.dart' as _i2;
import 'package:socket_io_client/src/socket.dart' as _i3;
import 'package:socket_io_common/src/util/event_emitter.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeManager_0 extends _i1.SmartFake implements _i2.Manager {
  _FakeManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSocket_1 extends _i1.SmartFake implements _i3.Socket {
  _FakeSocket_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Socket].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocket extends _i1.Mock implements _i3.Socket {
  @override
  String get nsp => (super.noSuchMethod(
        Invocation.getter(#nsp),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set nsp(String? _nsp) => super.noSuchMethod(
        Invocation.setter(
          #nsp,
          _nsp,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set opts(Map<dynamic, dynamic>? _opts) => super.noSuchMethod(
        Invocation.setter(
          #opts,
          _opts,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.Manager get io => (super.noSuchMethod(
        Invocation.getter(#io),
        returnValue: _FakeManager_0(
          this,
          Invocation.getter(#io),
        ),
        returnValueForMissingStub: _FakeManager_0(
          this,
          Invocation.getter(#io),
        ),
      ) as _i2.Manager);
  @override
  set io(_i2.Manager? _io) => super.noSuchMethod(
        Invocation.setter(
          #io,
          _io,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Socket get json => (super.noSuchMethod(
        Invocation.getter(#json),
        returnValue: _FakeSocket_1(
          this,
          Invocation.getter(#json),
        ),
        returnValueForMissingStub: _FakeSocket_1(
          this,
          Invocation.getter(#json),
        ),
      ) as _i3.Socket);
  @override
  set json(_i3.Socket? _json) => super.noSuchMethod(
        Invocation.setter(
          #json,
          _json,
        ),
        returnValueForMissingStub: null,
      );
  @override
  num get ids => (super.noSuchMethod(
        Invocation.getter(#ids),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as num);
  @override
  set ids(num? _ids) => super.noSuchMethod(
        Invocation.setter(
          #ids,
          _ids,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<dynamic, dynamic> get acks => (super.noSuchMethod(
        Invocation.getter(#acks),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);
  @override
  set acks(Map<dynamic, dynamic>? _acks) => super.noSuchMethod(
        Invocation.setter(
          #acks,
          _acks,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get connected => (super.noSuchMethod(
        Invocation.getter(#connected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set connected(bool? _connected) => super.noSuchMethod(
        Invocation.setter(
          #connected,
          _connected,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get disconnected => (super.noSuchMethod(
        Invocation.getter(#disconnected),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  set disconnected(bool? _disconnected) => super.noSuchMethod(
        Invocation.setter(
          #disconnected,
          _disconnected,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<dynamic> get sendBuffer => (super.noSuchMethod(
        Invocation.getter(#sendBuffer),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);
  @override
  set sendBuffer(List<dynamic>? _sendBuffer) => super.noSuchMethod(
        Invocation.setter(
          #sendBuffer,
          _sendBuffer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<dynamic> get receiveBuffer => (super.noSuchMethod(
        Invocation.getter(#receiveBuffer),
        returnValue: <dynamic>[],
        returnValueForMissingStub: <dynamic>[],
      ) as List<dynamic>);
  @override
  set receiveBuffer(List<dynamic>? _receiveBuffer) => super.noSuchMethod(
        Invocation.setter(
          #receiveBuffer,
          _receiveBuffer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set query(String? _query) => super.noSuchMethod(
        Invocation.setter(
          #query,
          _query,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set auth(dynamic _auth) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          _auth,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set subs(List<dynamic>? _subs) => super.noSuchMethod(
        Invocation.setter(
          #subs,
          _subs,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<dynamic, dynamic> get flags => (super.noSuchMethod(
        Invocation.getter(#flags),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);
  @override
  set flags(Map<dynamic, dynamic>? _flags) => super.noSuchMethod(
        Invocation.setter(
          #flags,
          _flags,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set id(String? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set pid(String? _pid) => super.noSuchMethod(
        Invocation.setter(
          #pid,
          _pid,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set lastOffset(String? _lastOffset) => super.noSuchMethod(
        Invocation.setter(
          #lastOffset,
          _lastOffset,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get active => (super.noSuchMethod(
        Invocation.getter(#active),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void subEvents() => super.noSuchMethod(
        Invocation.method(
          #subEvents,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Socket open() => (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
        ),
        returnValue: _FakeSocket_1(
          this,
          Invocation.method(
            #open,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_1(
          this,
          Invocation.method(
            #open,
            [],
          ),
        ),
      ) as _i3.Socket);
  @override
  _i3.Socket connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _FakeSocket_1(
          this,
          Invocation.method(
            #connect,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_1(
          this,
          Invocation.method(
            #connect,
            [],
          ),
        ),
      ) as _i3.Socket);
  @override
  _i3.Socket send(List<dynamic>? args) => (super.noSuchMethod(
        Invocation.method(
          #send,
          [args],
        ),
        returnValue: _FakeSocket_1(
          this,
          Invocation.method(
            #send,
            [args],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_1(
          this,
          Invocation.method(
            #send,
            [args],
          ),
        ),
      ) as _i3.Socket);
  @override
  void emit(
    String? event, [
    dynamic data,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #emit,
          [
            event,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emitWithAck(
    String? event,
    dynamic data, {
    Function? ack,
    bool? binary = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitWithAck,
          [
            event,
            data,
          ],
          {
            #ack: ack,
            #binary: binary,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void packet(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #packet,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onopen([dynamic _]) => super.noSuchMethod(
        Invocation.method(
          #onopen,
          [_],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void sendConnectPacket(Map<dynamic, dynamic>? data) => super.noSuchMethod(
        Invocation.method(
          #sendConnectPacket,
          [data],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onerror(dynamic err) => super.noSuchMethod(
        Invocation.method(
          #onerror,
          [err],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onclose(dynamic reason) => super.noSuchMethod(
        Invocation.method(
          #onclose,
          [reason],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onpacket(dynamic packet) => super.noSuchMethod(
        Invocation.method(
          #onpacket,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onevent(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #onevent,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  Function ack(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #ack,
          [id],
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as Function);
  @override
  void onack(Map<dynamic, dynamic>? packet) => super.noSuchMethod(
        Invocation.method(
          #onack,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onconnect(
    dynamic id,
    dynamic pid,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onconnect,
          [
            id,
            pid,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emitBuffered() => super.noSuchMethod(
        Invocation.method(
          #emitBuffered,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void ondisconnect() => super.noSuchMethod(
        Invocation.method(
          #ondisconnect,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void destroy() => super.noSuchMethod(
        Invocation.method(
          #destroy,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Socket close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _FakeSocket_1(
          this,
          Invocation.method(
            #close,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_1(
          this,
          Invocation.method(
            #close,
            [],
          ),
        ),
      ) as _i3.Socket);
  @override
  _i3.Socket disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _FakeSocket_1(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_1(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        ),
      ) as _i3.Socket);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Socket compress(dynamic compress) => (super.noSuchMethod(
        Invocation.method(
          #compress,
          [compress],
        ),
        returnValue: _FakeSocket_1(
          this,
          Invocation.method(
            #compress,
            [compress],
          ),
        ),
        returnValueForMissingStub: _FakeSocket_1(
          this,
          Invocation.method(
            #compress,
            [compress],
          ),
        ),
      ) as _i3.Socket);
  @override
  void on(
    String? event,
    _i4.EventHandler<dynamic>? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void once(
    String? event,
    _i4.EventHandler<dynamic>? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #once,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onAny(_i4.AnyEventHandler<dynamic>? handler) => super.noSuchMethod(
        Invocation.method(
          #onAny,
          [handler],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void off(
    String? event, [
    _i4.EventHandler<dynamic>? handler,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #off,
          [
            event,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void offAny([_i4.AnyEventHandler<dynamic>? handler]) => super.noSuchMethod(
        Invocation.method(
          #offAny,
          [handler],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void clearListeners() => super.noSuchMethod(
        Invocation.method(
          #clearListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool hasListeners(String? event) => (super.noSuchMethod(
        Invocation.method(
          #hasListeners,
          [event],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
